project: 
  type: website
  output-dir: docs

website:
  title: "Alayna Daws Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "Master of Science Thesis"
            href: ./Thesis.html
          - text: "Undergraduate Honors Projects"
            href: ./Honors.html
          - text: "Statisticial Capstone Report"
            href: ./Capstone.html
          - text: "Sampling Analysis"
            href: ./firefly.html

    right:
      - icon: github 
        href: https://alayna-d.github.io/portfolio/      

format:
  html:
    theme: lux
    highlight: zenburn
    css: styles.css
    toc: FALSE



