project: 
  type: website
  output-dir: docs

website:
  title: "Alayna Daws Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "Year In Review - Customer Report"
            href: ./whyir2024.html
          - text: "Master of Science Thesis"
            href: ./Thesis.html
          - text: "Phylogenetic Analysis Project"
            href: ./Honors.html
          - text: "Statisticial Capstone Report"
            href: ./Capstone.html
          - text: "Sampling Analysis"
            href: ./firefly.html

    right:
      - icon: github 
        href: https://github.com/AlaynaD1?tab=repositories
      - icon: linkedin
        href: https://www.linkedin.com/in/alayna1785

format:
  html:
    theme: lux
    highlight: zenburn
    css: styles.css
    toc: FALSE



