---
title: "Statistical Capstone Report"
output: 
  html_document:
    toc: FALSE
title-block-banner: "#3399FF"
engine: knitr 
cv:
  pdf: "CapstoneCompleteReport.pdf"
---
# Discovering the Most Effective Repellents to Ward off Unwanted Elephants

I collaborated with two other capstone students to design an experiment, complete exploratory data analysis, and provide expected results for an experiment centered around bull elephants in Zimbabwe. In Zimbabwe, farmers’ crops have been trampled and eaten, tourists have been negatively impacted, and local communities have faced destruction as a result of the bull elephants. The purpose of the project was to determine which repellent was most effective at keeping bull elephants away from specific areas in the region. The end goal was to create a solution that was low cost, low maintenance, with minimal negative impact to elephant health, and to quantify animal behavior.

```{css, echo=FALSE}
#title-block-header .description {
    display: none;
}
```

```{css echo=FALSE}
.embed-container {
    position: relative;
    padding-bottom: 129%;
    height: 0;
    overflow: hidden;
    max-width: 100%;
}

.embed-container iframe,
.embed-container object,
.embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$cv$pdf`" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download Report
  </a>
</p>

<div class="embed-container">
  <iframe src="`r rmarkdown::metadata$cv$pdf`" style="border: 0.5px"></iframe>
</div>
```

