---
title: "Sampling Analysis"
output: 
  html_document:
    toc: FALSE
title-block-banner: "#FFCC00"
engine: knitr 
cv:
  pdf: "FireflyRiipenProject.pdf"
---
# Firefly Partners, LLC Sampling Analysis

Alongside two other Statistics students, we collaborated to design and implement a survey on behalf of Firefly Partners, LLC. I was drawn to the Firefly Partners, LLC project because the digital marketing agency is women-owned and delivers solutions that help progressive nonprofits achieve goals. The partnership was facilitated through Riipen, a service that connects companies that need help solving problems relevant to their business model with suitable university courses. The purpose of the survey was to gather qualitative and quantitative data to tell the story of Firefly's work and how effective their partnerships have been in creating positive change. After the conclusion of the survey, the data was analyzed using R and the findings were presented to representatives at Firefly Partners, LLC. This helped Firefly Partners, LLC tailor their experience to better accommodate current and future users.

```{css, echo=FALSE}
#title-block-header .description {
    display: none;
}
```

```{css echo=FALSE}
.embed-container {
    position: relative;
    padding-bottom: 129%;
    height: 0;
    overflow: hidden;
    max-width: 100%;
}

.embed-container iframe,
.embed-container object,
.embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$cv$pdf`" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download Presentation
  </a>
</p>

<div class="embed-container">
  <iframe src="`r rmarkdown::metadata$cv$pdf`" style="border: 0.5px"></iframe>
</div>
```

