---
title: "Undergraduate Honors Projects"
output: 
  html_document:
    toc: FALSE
title-block-banner: "#009966"
engine: knitr 
cv:
  pdf: "HonorsOption.pdf"
---
# Phylogenetic Analysis - COVID-19

Many SARS-CoV-2 variants have been identified through genetic sequencing. During
the duration of the COVID-19 pandemic, there have been five variants considered to be
a “variant of concern (VOCs)” by the World Health Organization. These five were
identified as VOCs based on their impact on global public health. The five variants are
identified as Alpha, Beta, Gamma, Delta, and Omicron. Alpha, Beta, and Gamma are
classified as previously circulating. Delta and Omicron are considered to be currently
circulating VOCs. Omicron is believed to exemplify a 13-fold increase in viral infectivity
and is 2.8 times more infectious than the Delta variant (Cascella et.al 2022).

The goal of this report was to see if the Delta and Omicron variant trends within the data
can be identified based on phylogenetic clades. This was completed by analyzing the 
dates the samples were taken and comparing this to the variant more prominent at the
time based on the COVID-19 timeline provided by the Centers for Disease Control and
Prevention.

```{css, echo=FALSE}
#title-block-header .description {
    display: none;
}
```

```{css echo=FALSE}
.embed-container {
    position: relative;
    padding-bottom: 129%;
    height: 0;
    overflow: hidden;
    max-width: 100%;
}

.embed-container iframe,
.embed-container object,
.embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$cv$pdf`" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download Phylogenetic Analysis - COVID-19 Report
  </a>
</p>

<div class="embed-container">
  <iframe src="`r rmarkdown::metadata$cv$pdf`" style="border: 0.5px"></iframe>
</div>
```

# R Shiny Student Loan Information Application

Attached, you will find the link to a student loan information application I developed utilizing R Shiny. This application utilizes data visualization to allow for better understanding of the 2019 Survey of Consumer Finances. This survey recorded individuals with a total debt level above $100,000 where gender, race, and age were visualized. I also completed an honors tab where I investigated debt levels for very high debt, demographic breakdowns, education level, and current income levels. 

[Student Loan Information App](https://statadaws.shinyapps.io/finalapphonorsadaws/)  
