---
title: "Year In Review - Customer Report"
output: 
  html_document:
    toc: FALSE
title-block-banner: "#9BCB4B"
engine: knitr 
cv:
  pdf: "2024_Year_In_Review_Industry.pdf"
---
# 2024 Year In Review Report WelcomeHome Software

I led the creation of the 2024 Year In Review report, the most significant annual piece of collateral from the customer insights function. This year, I focused on driving key technical improvements—like process automation, ensuring data fidelity, and leading feedback efforts with our partners. By streamlining production and juggling multiple timelines, I was able to boost both scalability and quality. The report draws from real-time data across thousands of communities in primary, secondary, and tertiary markets, covering all 50 states, with insights from millions of prospects and customers using WelcomeHome’s CRM.

We expanded our analysis, integrated more feedback, and revamped marketing content to better tell the story behind the data. I also led and presented at multiple webinars to share key takeaways and best practices, helping senior living leaders make informed decisions. This content played a crucial role in the prospect journey, aligning with Sales to convert prospects into customers.

Collaboration was essential this year. Working closely with Marketing, Sales, and CX, I helped solve technical challenges and strengthen feedback loops, delivering actionable insights to help the senior living industry thrive in 2025. This report set a new company record, achieving the highest number of downloads in our history and attracting the most webinar attendees ever. I also added new sections to the report, including detailed prospect journeys to support sales directors and an in-depth analysis of move-out reasons to further enhance strategies.

I've included a PDF of a few pages from the full report below, or you can download the complete [2024 Year in Review report here](https://info.welcomehomesoftware.com/yearinreview-2024?utm_campaign=4720422-2024%20Year%20In%20Review&utm_source=direct&utm_medium=alayna).

```{css, echo=FALSE}
#title-block-header .description {
    display: none;
}
```

```{css echo=FALSE}
.embed-container {
    position: relative;
    padding-bottom: 129%;
    height: 0;
    overflow: hidden;
    max-width: 100%;
}

.embed-container iframe,
.embed-container object,
.embed-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg cv-download" href="`r rmarkdown::metadata$cv$pdf`" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download Report
  </a>
</p>

<div class="embed-container">
  <iframe src="`r rmarkdown::metadata$cv$pdf`" style="border: 0.5px"></iframe>
</div>
```

